### PR TITLE
Final preparations for release

### PR DESCRIPTION
**Pull request by jjatria**
First, I apologise for the big patch. This includes a number of small fixes meant to bring this plugin to a relase-ready status. It includes some added features (like the new tests introduced in 0ae0950), some general fixes (dddd957, 262bf55) and simplifies the interface a little, making it more general. In brief, it makes the plugin into a stricter implementation of the spec.

In particular:

* It **removes** support for comments in labels (b633381). I understand why this would be good to have, but there is no generalisable way of making this work.

* It **removes** support for trimming "context" from labels (4ae8e9e). The spec makes no assumptions about the content of the labels (other than the implicit one about them having no spaces), so I think neither should this plugin. And it is trivial to implement this kind of filtering in a more specific plugin at a later date, as we discussed previously.

* It **removes** the option of opening Sound with the label to adjust the timings (4ae8e9e). Again: if the spec is for annotations, we should not assume that the accompanying sound even exists. It shouldn't be necessary to have it, and it only complicates the interface. And like before, it is trivial to make those time adjustments ina  more specific plugin.

* It **removes** the changes in `setup.praat` that change the behaviour of Praat depending on the value of environment variables. Like we discussed, this would be better implemented as a separate, more specific plugin.

* It reinstates the `timestamps.proc` file removed originally in cdad59c. I'm not sure why this was removed, actually. The reason for it to be there is that both the reading and writing procedures use it, and having it reduces the amount of repeated code. It also means that the read and the write files are independent, so they do not need to include each other.

* It updates the readme file to match these changes.

* It adds a change log that was somehow missing (?)

### CODE REVIEW

**Comment by CShulby** [comment]
sounds great!  I will take a look :-)

2017-06-15 9:28 GMT-03:00 José Joaquín Atria <notifications@github.com>:

**Comment by jjatria** [comment]
And then we can take a look at the HTS-review plugin you were talking about :+1:

**Comment by jjatria** [comment]
By the way, I'm preparing a workshop for a conference next week in Málaga, and I'd like to mention this plugin as an example of things that people might find useful. Do you think you could take a look before Tuesday, so I can push it out in time?

I know it's super late notice, but the good thing is that future versions can always adjust things, and I think this patch brings things pretty close to a ready first version. Let me know! :D

**Comment by CShulby** [comment]
sure! I was going to do this on Monday but I will make time to check it out
tomorrow.

2017-06-16 17:37 GMT-03:00 José Joaquín Atria <notifications@github.com>:

**Comment by CShulby** [comment]
ok, so now the idea is that the user should load the sound file separately?
This is fine I think.  I will take the strings object out as well (it is
loading still which I had done in order to save the information with the
comments). This should be removed as well to go along with the new logic)

2017-06-16 21:06 GMT-03:00 Christopher Shulby <chrisshulby@gmail.com>:

**Comment by CShulby** [comment]
How is it going with the release?

Am 17.06.2017 1:23 nachm. schrieb "Christopher Shulby" <
chrisshulby@gmail.com>:

**Comment by jjatria** [comment]
It's done! :D

* The plugin on the CPrAN website:
  http://cpran.net/plugins/htklabel

* The CPrAN mirror for the source (currently mirrored from my fork, but we can change that): 
  https://gitlab.com/cpran/plugin_htklabel

* The plugin on the remote "database": 
  https://gitlab.com/cpran/plugin_cpran/snippets/16130#L1-30

**Comment by CShulby** [comment]
awesome.  Does it get the package straight from get or does it need to be
updated with stable versions?

2017-06-20 18:18 GMT-03:00 José Joaquín Atria <notifications@github.com>:

**Comment by jjatria** [comment]
It gets the packages from tagged commits in git. So whenever we reach a stable version, we tag it and push the tag. As long as the tag is properly formatted (`v#.#.#`, as a [semantic version](http://semver.org)), then that will be recognised as a new version that can be installed.

(That's why for now I mirrored my fork, in which e7e3521 is tagged as [`v0.0.1`](https://gitlab.com/cpran/plugin_htklabel/tags/v0.0.1))

**Pull request merged**
